### ISSUE TITLE
Cannot install phasepy in 3.10 on Windows Environment: Getting Requirements to build wheel did not run successfully

### ISSUE THREAD

**Issue by basementcrusader** [gustavochm/phasepy#17]
Hi, I'm trying to install phasepy on my windows machine using python 3.10. Use many other python packages already and I made sure that I wasn't missing cython but to no avail.

Attached is the command line output.

> pip install phasepy
> Collecting phasepy
>   Using cached phasepy-0.0.51.tar.gz (222 kB)
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... error
>   error: subprocess-exited-with-error
> 
>   × Getting requirements to build wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [17 lines of output]
>       Traceback (most recent call last):
>         File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
>           main()
>         File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
>           json_out['return_val'] = hook(**hook_input['kwargs'])
>         File "C:\Users\me\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
>           return hook(config_settings)
>         File "C:\Users\me\AppData\Local\Temp\pip-build-env-5n_vq2f_\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
>           return self._get_build_requires(config_settings, requirements=['wheel'])
>         File "C:\Users\me\AppData\Local\Temp\pip-build-env-5n_vq2f_\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
>           self.run_setup()
>         File "C:\Users\me\AppData\Local\Temp\pip-build-env-5n_vq2f_\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
>           super(_BuildMetaLegacyBackend,
>         File "C:\Users\me\AppData\Local\Temp\pip-build-env-5n_vq2f_\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
>           exec(code, locals())
>         File "<string>", line 35, in <module>
>       NameError: name 'build_ext' is not defined
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully.
> │ exit code: 1
> ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by gustavochm** [comment]
Hey, sorry for the problem.
Last time it tried to use python 3.10 I also faced a compatibility issue with python. do you need to stick to python 3.10? If not you could please try using python 3.9? Python 3.9 (and others 3.8, 3.7, 3.6) work just fine.

Gustavo

**Comment by basementcrusader** [comment]
Hi Gustavo,

Thank you for your prompt reply. It would make it much easier to work on what I'm trying to do with 3.10+

Update: Python 3.9 functionality with phasepy is somewhat successful, though conda will not install it from a prompt window

**Comment by Sherlock898** [comment]
Did you install cython?
